# Generated by Django 3.2 on 2026-10-04 03:41

import authentication.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=authentication.models.generate_object_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwordHash', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('displayPicture', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isVerified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otpExpiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
