# Generated by Django 3.2 on 2026-10-04 03:41

import authentication.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=authentication.models.generate_object_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=50)),
                ('credentials', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.CharField(default=authentication.models.generate_object_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('scannedResources', models.IntegerField()),
                ('totalChecks', models.IntegerField(blank=True, default=0, null=True)),
                ('skippedChecks', models.TextField(blank=True, null=True)),
                ('criticalCount', models.IntegerField(default=0)),
                ('highCount', models.IntegerField(default=0)),
                ('mediumCount', models.IntegerField(default=0)),
                ('findings', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project')),
            ],
        ),
    ]
