# Generated by Django 3.2 on 2026-10-04 03:41

import authentication.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSchedule',
            fields=[
                ('id', models.CharField(default=authentication.models.generate_object_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=50)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('daysOfWeek', models.JSONField(blank=True, default=list, null=True)),
                ('dayOfMonth', models.IntegerField(blank=True, null=True)),
                ('credentials', models.TextField(blank=True, null=True)),
                ('lastRun', models.DateTimeField(blank=True, null=True)),
                ('nextRun', models.DateTimeField()),
                ('targetEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.project')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='authentication.user')),
            ],
        ),
    ]
